version: '3'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./files:/var/www/html:delegated
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql:delegated
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db